#!/usr/bin/env python3
"""
adjudicate_stems.py
Step 5 — recover the compound links LSJ's hyphenation hides.

LSJ hyphenates only the LAST morpheme boundary of a headword. When a compound
ends in a derivational suffix, the hyphen marks the suffix and the compound seam
is invisible:

    δημοκρατία   LSJ: dhmokra^t-i/a   ->  δημοκρατ|ία   (δημο+κρατ seam hidden)
    μυθολογία    LSJ: mu_qolog-i/a    ->  μυθολογ|ία
    στρατηγός    LSJ: strathg-o/s     ->  στρατηγ|ός

and some compounds are not hyphenated at all (φιλόσοφος, θεολογία).

So for each candidate this pass enumerates every internal split whose two halves
resolve to real lemmas holding families (done locally, free), then asks the model
to pick the correct split — or none — and confirm which family links are genuine.

Many candidates in the second bucket are NOT compounds at all (ἐργάζομαι,
ἀλλότριος, ἀμφότερος, στοιχεῖον). Answering "no split" for those is a correct
and expected outcome, not a failure.

Uses the Batch API with Sonnet 5 (50% off). Reads ANTHROPIC_API_KEY from env.

Usage:
    python3 adjudicate_stems.py build
    python3 adjudicate_stems.py submit --limit 450
    python3 adjudicate_stems.py status
    python3 adjudicate_stems.py fetch
    python3 adjudicate_stems.py apply --min-confidence 0.8 --write
"""

import argparse
import json
import os
import re
import sqlite3
import sys
from pathlib import Path

HERE = Path(__file__).parent
AUDIT = HERE / "family_audit"
DB_PATH = HERE / "greek_vocab.db"

PAYLOADS = AUDIT / "stem_split_payloads.json"
REQ_FILE = AUDIT / "stem_batch_requests.json"
IDS_FILE = AUDIT / "stem_batch_ids.txt"
RES_FILE = AUDIT / "stem_batch_results.jsonl"
VERDICTS = AUDIT / "stem_verdicts.json"

MODEL = "claude-sonnet-5"
PER_REQUEST = 6
PRICE_IN, PRICE_OUT = 2.00 / 2, 10.00 / 2      # Sonnet 5, batch discount

SYSTEM_PROMPT = """You are a specialist in Ancient Greek historical and derivational morphology.

Each item is a Greek word together with candidate ways of splitting it into two morphemes, and the word families each split would connect it to. The candidate splits were generated by string matching, so most are wrong.

Your job, per word:
1. Decide whether the word is genuinely a COMPOUND of two lexical morphemes.
2. If it is, pick the single correct split.
3. Accept only the family links that reflect real morphological derivation.

Accept a link when the word really contains that root, including in combining form (δημο- for δῆμος, μυθο- for μῦθος, στρατ- for στρατός, φιλο- for φίλος, γεω- for γῆ, θεο- for θεός) and under regular sound change (σύν → συμ-/συγ-/συλ-, ἐκ → ἐξ-, ἀπό → ἀφ-).

Answer with split=null and an empty accept list when the word is NOT a compound. Many of these are simplex and only look long:
- ἐργάζομαι, ἀλλότριος, ἀμφότερος, στοιχεῖον, ἀφικνέομαι are not compounds of two lexemes.
- A stem plus a derivational suffix (-σύνη, -ματ-, -τηριον, -ικος) is NOT a compound.

Reject links that come from:
- proper nouns matched by coincidence (Ζώπυρος, Τήριλλος, Μανεθώς, Ἄνδρος)
- a suffix mistaken for a word (-ίτης is not ἴτης; -τειρα is not Εἴρα)
- homonyms and bare letter overlap with no morphological relation

Return ONLY a JSON array, no prose, no markdown fence:
[{"headword":"...","split":"δημο|κρατ"|null,"accept_family_ids":[123,456],"confidence":0.0-1.0,"reason":"<12 words max>"}]

Give every word an entry. Use confidence below 0.7 when genuinely unsure."""


def get_client():
    if not os.environ.get("ANTHROPIC_API_KEY"):
        sys.exit("ERROR: ANTHROPIC_API_KEY is not set in this shell.")
    import anthropic
    return anthropic.Anthropic()


def cmd_build(args):
    payloads = json.loads(PAYLOADS.read_text(encoding="utf-8"))
    # Most frequent words first, so an interrupted run still covers what matters.
    payloads.sort(key=lambda p: -p.get("occurrences", 0))
    reqs = []
    for i in range(0, len(payloads), PER_REQUEST):
        chunk = payloads[i:i + PER_REQUEST]
        reqs.append({
            "custom_id": f"stem-{i:06d}",
            "params": {
                "model": MODEL,
                "max_tokens": 8000,
                "system": [{"type": "text", "text": SYSTEM_PROMPT,
                            "cache_control": {"type": "ephemeral"}}],
                "messages": [{"role": "user", "content":
                              "Analyse each word:\n\n" +
                              json.dumps(chunk, ensure_ascii=False, indent=1)}],
            },
        })
    AUDIT.mkdir(exist_ok=True)
    REQ_FILE.write_text(json.dumps(reqs, ensure_ascii=False), encoding="utf-8")
    print(f"words            : {len(payloads)}")
    print(f"split options    : {sum(len(p['possible_splits']) for p in payloads)}")
    print(f"requests ({PER_REQUEST}/req): {len(reqs)}")
    print(f"-> {REQ_FILE.relative_to(HERE)}")


def cmd_submit(args):
    client = get_client()
    reqs = json.loads(REQ_FILE.read_text(encoding="utf-8"))
    done = set()
    if IDS_FILE.exists():
        for line in IDS_FILE.read_text().splitlines():
            if line.strip() and "\t" in line:
                _, lo, hi = line.split("\t")
                done.update(range(int(lo), int(hi)))
    todo = [i for i in range(len(reqs)) if i not in done]
    if not todo:
        print("All requests already submitted.")
        return
    take = todo[:args.limit]
    batch = client.messages.batches.create(requests=[reqs[i] for i in take])
    with IDS_FILE.open("a") as fh:
        fh.write(f"{batch.id}\t{take[0]}\t{take[-1]+1}\n")
    print(f"submitted {batch.id}: requests {take[0]}..{take[-1]} "
          f"({len(take)} of {len(reqs)}), remaining {len(todo)-len(take)}")


def cmd_status(args):
    client = get_client()
    for line in IDS_FILE.read_text().splitlines():
        if not line.strip():
            continue
        bid, lo, hi = line.split("\t")
        b = client.messages.batches.retrieve(bid)
        c = b.request_counts
        print(f"{bid}  [{lo}..{hi})  {b.processing_status}  succeeded={c.succeeded} "
              f"errored={c.errored} processing={c.processing}")


def cmd_fetch(args):
    client = get_client()
    seen = set()
    if RES_FILE.exists():
        for line in RES_FILE.read_text(encoding="utf-8").splitlines():
            if line.strip():
                seen.add(json.loads(line)["custom_id"])
    n = 0
    with RES_FILE.open("a", encoding="utf-8") as fh:
        for line in IDS_FILE.read_text().splitlines():
            if not line.strip():
                continue
            bid = line.split("\t")[0]
            b = client.messages.batches.retrieve(bid)
            if b.processing_status != "ended":
                print(f"{bid} not finished ({b.processing_status}) — skipping")
                continue
            for result in client.messages.batches.results(bid):
                if result.custom_id in seen:
                    continue
                rec = {"custom_id": result.custom_id, "type": result.result.type}
                if result.result.type == "succeeded":
                    msg = result.result.message
                    rec["text"] = "".join(x.text for x in msg.content if x.type == "text")
                    rec["usage"] = {"input_tokens": msg.usage.input_tokens,
                                    "output_tokens": msg.usage.output_tokens}
                else:
                    rec["error"] = str(getattr(result.result, "error", ""))
                fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
                n += 1
    print(f"fetched {n} new results")
    ti = to = rows = 0
    for line in RES_FILE.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        u = json.loads(line).get("usage")
        if u:
            rows += 1
            ti += u["input_tokens"]
            to += u["output_tokens"]
    cost = ti / 1e6 * PRICE_IN + to / 1e6 * PRICE_OUT
    print(f"\nACTUAL over {rows} requests: input {ti:,} output {to:,}")
    print(f"ACTUAL COST SO FAR: ${cost:.2f}" + (f"  (${cost/rows:.4f}/req)" if rows else ""))


def parse_all():
    out, bad = [], 0
    for line in RES_FILE.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        if r.get("type") != "succeeded":
            continue
        txt = re.sub(r"^```(?:json)?|```$", "", r["text"].strip(), flags=re.M).strip()
        try:
            out.extend(json.loads(txt))
        except json.JSONDecodeError:
            m = re.search(r"\[.*\]", txt, re.S)
            if m:
                try:
                    out.extend(json.loads(m.group(0)))
                    continue
                except json.JSONDecodeError:
                    pass
            bad += 1
    return out, bad


def build_sanitizer(db):
    """Redirect links that point at a lookalike family instead of the real preverb.

    The candidate generator matches by string, so a συν- compound can be offered
    family 17463 "Root: συ- (2nd person pronoun)" — σύ, σός — because συμ-/συγ-
    starts with συ. The model then accepts it while reasoning correctly that σύν
    assimilated. The morphology is right; only the family id is wrong, so the
    link is redirected to the canonical preposition family rather than dropped.
    """
    from build_prepositions import ALLOMORPHS, bare as _bare
    canon = {r: f for f, r in db.execute(
        "SELECT id, root FROM derivational_families WHERE label LIKE '%preposition/preverb%'")}
    famroot = {r[0]: _bare(r[1] or "").strip("-_ ")
               for r in db.execute("SELECT id, root FROM derivational_families")}
    prepfids = set(canon.values())

    def sanitize(split, fids):
        if not split or "|" not in str(split):
            return list(fids), 0
        first = _bare(str(split).split("|")[0]).strip("-_ ")
        prep = next((c for f, c in ALLOMORPHS if first == f), None)
        if not prep:
            return list(fids), 0
        target, out, fixed = canon.get(prep), [], 0
        for fid in fids:
            r = famroot.get(fid, "")
            if (fid not in prepfids and r and len(r) <= 4
                    and (first.startswith(r) or r.startswith(first))):
                if target:
                    out.append(target)
                    fixed += 1
            else:
                out.append(fid)
        return out, fixed
    return sanitize


def cmd_apply(args):
    verdicts, bad = parse_all()
    VERDICTS.write_text(json.dumps(verdicts, ensure_ascii=False, indent=1), encoding="utf-8")
    split = [v for v in verdicts if v.get("split")]
    db = sqlite3.connect(str(DB_PATH))
    sanitize = build_sanitizer(db)

    links, redirected = [], 0
    for v in verdicts:
        if float(v.get("confidence", 0)) < args.min_confidence:
            continue
        fids, fixed = sanitize(v.get("split"), v.get("accept_family_ids") or [])
        redirected += fixed
        for fid in fids:
            links.append((v, fid))

    print(f"words judged    : {len(verdicts)}  (unparseable responses: {bad})")
    print(f"  ruled COMPOUND: {len(split)}")
    print(f"  ruled simplex : {len(verdicts) - len(split)}")
    print(f"  links >= {args.min_confidence} : {len(links)}")
    print(f"  redirected off lookalike families: {redirected}")
    if not args.write:
        print("\n(dry run — pass --write to apply)")
        db.close()
        return

    payloads = {p["headword"]: p for p in json.loads(PAYLOADS.read_text(encoding="utf-8"))}
    lid_of = {}
    for hw in payloads:
        row = db.execute("SELECT id FROM lemmas WHERE lemma=?", (hw,)).fetchone()
        if row:
            lid_of[hw] = row[0]
    added = 0
    for v, fid in links:
        lid = lid_of.get(v["headword"])
        if not lid:
            continue
        if db.execute("SELECT 1 FROM lemma_families WHERE lemma_id=? AND family_id=?",
                      (lid, fid)).fetchone():
            continue
        if not db.execute("SELECT 1 FROM derivational_families WHERE id=?", (fid,)).fetchone():
            continue
        db.execute("""INSERT INTO lemma_families
                      (lemma_id, family_id, relation, derivation_type)
                      VALUES (?,?,?,?)""",
                   (lid, fid, "compound element", "compound_stem"))
        db.execute("""INSERT INTO family_edit_log (action, family_id, lemma_id, detail, user)
                      VALUES ('add_member',?,?,?,'adjudicate_stems')""",
                   (fid, lid, json.dumps({"relation": "compound element",
                                          "split": v.get("split"),
                                          "confidence": v.get("confidence"),
                                          "reason": v.get("reason")}, ensure_ascii=False)))
        added += 1
    db.commit()
    db.close()
    print(f"\napplied {added} new family links")


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("build").set_defaults(func=cmd_build)
    p = sub.add_parser("submit")
    p.add_argument("--limit", type=int, default=450)
    p.set_defaults(func=cmd_submit)
    sub.add_parser("status").set_defaults(func=cmd_status)
    sub.add_parser("fetch").set_defaults(func=cmd_fetch)
    p = sub.add_parser("apply")
    p.add_argument("--min-confidence", type=float, default=0.8)
    p.add_argument("--write", action="store_true")
    p.set_defaults(func=cmd_apply)
    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
