# fly.toml app configuration file generated for glossalearn-api on 2026-03-11T23:36:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'glossalearn-api'
primary_region = 'ord'

[build]

[env]
  GLOSSALEARN_SUPERUSER = '0'

[[mounts]]
  source = 'glossalearn_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/api/status"

[[vm]]
  memory = '1gb'
  cpus = 1
